import subprocess
import os
import sys

import subprocess
import os
import sys
import shutil

def call_sub_agent(prompt, verbose=True, input_files=None):
    """
    Dispatches a task to the sub-agent environment via bin/run_agent.sh.
    
    Args:
        prompt (str): The instruction for the sub-agent.
        verbose (bool): Whether to print status messages.
        input_files (dict): Map of {destination_filename: source_path} to stage in workspace.
        
    Returns:
        str: The content generated by the sub-agent, or None on failure.
    """
    
    # Resolve paths relative to this script
    script_dir = os.path.dirname(os.path.abspath(__file__))
    bash_script = os.path.join(script_dir, "bin", "run_agent.sh")
    workspace_dir = os.path.join(script_dir, "workspace")
    os.makedirs(workspace_dir, exist_ok=True)

    # --- WORKSPACE HYGIENE ---
    if verbose:
        print(f"[Status] Cleaning workspace: {workspace_dir}")
    for item in os.listdir(workspace_dir):
        item_path = os.path.join(workspace_dir, item)
        try:
            if os.path.isfile(item_path) or os.path.islink(item_path):
                os.unlink(item_path)
            elif os.path.isdir(item_path):
                shutil.rmtree(item_path)
        except Exception as e:
            print(f"Warning: Failed to delete {item_path}: {e}")

    # --- STAGING ---
    if input_files:
        for dest_name, src_path in input_files.items():
            if os.path.exists(src_path):
                if verbose:
                    print(f"[Status] Staging: {os.path.basename(src_path)} -> {dest_name}")
                shutil.copy(src_path, os.path.join(workspace_dir, dest_name))
            else:
                # If src_path is not a file, treat it as direct content if appropriate?
                # Actually, better to keep it simple: assume path.
                if verbose:
                    print(f"[Warning] Source file not found for staging: {src_path}")

    # Write prompt to task_prompt.md for consistent interface
    with open(os.path.join(workspace_dir, "task_prompt.md"), 'w', encoding='utf-8') as f:
        f.write(prompt)
    
    # Locate Bash executable
    # Prioritize environment variable, then common paths, then PATH
    bash_exe = os.environ.get("BASH_EXE")
    if not bash_exe:
        if sys.platform == "win32":
            common_paths = [
                r"C:\Program Files\Git\bin\bash.exe",
                r"C:\Program Files (x86)\Git\bin\bash.exe",
            ]
            for path in common_paths:
                if os.path.exists(path):
                    bash_exe = path
                    break
    
    if not bash_exe:
        bash_exe = "bash" # Hope it's in PATH

    if verbose:
        print(f"--- Dispatching Agent Task ---")
        preview = prompt[:50] + "..." if len(prompt) > 50 else prompt
        print(f"Prompt: {preview}")

    try:
        # Run the bash script and stream output in real-time
        # We pass "__USE_EXISTING__" if we want it to read task_prompt.md
        # but the wrapper usually handles the prompt string directly too.
        # To support the new cleaning logic, we should probably always use task_prompt.md.
        
        process = subprocess.Popen(
            [bash_exe, bash_script, "__USE_EXISTING__"],
            stdout=subprocess.PIPE,
            stderr=subprocess.STDOUT,
            text=True,
            encoding='utf-8',
            bufsize=1
        )
        
        output_lines = []
        if verbose:
            print(f"--- Sub-Agent Session Started ---")

        for line in process.stdout:
            print(line, end="")
            output_lines.append(line)
        
        process.wait()
        
        if verbose:
            print(f"--- Sub-Agent Session Finished (Exit Code: {process.returncode}) ---")

        if process.returncode != 0:
            print(f"Error executing agent script.")
            return None

        # Read the output file directly
        output_file = os.path.join(workspace_dir, "task_output.md")
        
        if os.path.exists(output_file):
            with open(output_file, 'r', encoding='utf-8') as f:
                content = f.read().strip()
                return content
        else:
            print("Error: Output file not found.")
            return None

    except Exception as e:
        print(f"Exception during agent dispatch: {e}")
        return None

if __name__ == "__main__":
    if len(sys.argv) < 2:
        print("Usage: python sub_agent.py \"<Prompt Text or File Path>\"")
        sys.exit(1)
    
    input_val = sys.argv[1]
    
    # Check if input is a file path
    if os.path.isfile(input_val):
        print(f"Reading prompt from file: {input_val}")
        try:
            with open(input_val, 'r', encoding='utf-8') as f:
                user_prompt = f.read()
        except Exception as e:
            print(f"Error reading prompt file: {e}")
            sys.exit(1)
    else:
        # Join all arguments as the prompt
        user_prompt = " ".join(sys.argv[1:])
    
    call_sub_agent(user_prompt)
