import subprocess
import os
import sys

def call_sub_agent(prompt, verbose=True):
    """
    Dispatches a task to the sub-agent environment via bin/run_agent.sh.
    
    Args:
        prompt (str): The instruction for the sub-agent.
        verbose (bool): Whether to print status messages.
        
    Returns:
        str: The content generated by the sub-agent, or None on failure.
    """
    
    # Resolve paths relative to this script
    script_dir = os.path.dirname(os.path.abspath(__file__))
    bash_script = os.path.join(script_dir, "bin", "run_agent.sh")
    workspace_dir = os.path.join(script_dir, "workspace")
    
    # Locate Bash executable
    # Prioritize environment variable, then common paths, then PATH
    bash_exe = os.environ.get("BASH_EXE")
    if not bash_exe:
        if sys.platform == "win32":
            common_paths = [
                r"C:\Program Files\Git\bin\bash.exe",
                r"C:\Program Files (x86)\Git\bin\bash.exe",
            ]
            for path in common_paths:
                if os.path.exists(path):
                    bash_exe = path
                    break
    
    if not bash_exe:
        bash_exe = "bash" # Hope it's in PATH

    if verbose:
        print(f"--- Dispatching Agent Task ---")
        preview = prompt[:50] + "..." if len(prompt) > 50 else prompt
        print(f"Prompt: {preview}")

    try:
        # Run the bash script
        # We capture stdout/stderr to extract the result cleanly if needed
        result = subprocess.run(
            [bash_exe, bash_script, prompt],
            capture_output=True,
            text=True,
            encoding='utf-8' 
        )
        
        if result.returncode != 0:
            print(f"Error executing agent script: {result.stderr}")
            return None

        # Read the output file directly
        output_file = os.path.join(workspace_dir, "task_output.md")
        
        if os.path.exists(output_file):
            with open(output_file, 'r', encoding='utf-8') as f:
                content = f.read().strip()
                if verbose:
                    print(f"--- Agent Result ---\n{content}\n--------------------")
                return content
        else:
            print("Error: Output file not found.")
            return None

    except Exception as e:
        print(f"Exception during agent dispatch: {e}")
        return None

if __name__ == "__main__":
    if len(sys.argv) < 2:
        print("Usage: python sub_agent.py \"<Prompt Text or File Path>\"")
        sys.exit(1)
    
    input_val = sys.argv[1]
    
    # Check if input is a file path
    if os.path.isfile(input_val):
        print(f"Reading prompt from file: {input_val}")
        try:
            with open(input_val, 'r', encoding='utf-8') as f:
                user_prompt = f.read()
        except Exception as e:
            print(f"Error reading prompt file: {e}")
            sys.exit(1)
    else:
        # Join all arguments as the prompt
        user_prompt = " ".join(sys.argv[1:])
    
    call_sub_agent(user_prompt)
